In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
df = pd.read_csv('AirQualityUCI.csv', sep=';')

In [3]:
df.head()

Date      Time CO(GT)  PT08.S1(CO)  NMHC(GT) C6H6(GT)  PT08.S2(NMHC)  \
0  10/03/2004  18.00.00    2,6       1360.0     150.0     11,9         1046.0   
1  10/03/2004  19.00.00      2       1292.0     112.0      9,4          955.0   
2  10/03/2004  20.00.00    2,2       1402.0      88.0      9,0          939.0   
3  10/03/2004  21.00.00    2,2       1376.0      80.0      9,2          948.0   
4  10/03/2004  22.00.00    1,6       1272.0      51.0      6,5          836.0   

   NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)     T    RH  \
0    166.0        1056.0    113.0        1692.0       1268.0  13,6  48,9   
1    103.0        1174.0     92.0        1559.0        972.0  13,3  47,7   
2    131.0        1140.0    114.0        1555.0       1074.0  11,9  54,0   
3    172.0        1092.0    122.0        1584.0       1203.0  11,0  60,0   
4    131.0        1205.0    116.0        1490.0       1110.0  11,2  59,6   

       AH  Unnamed: 15  Unnamed: 16  
0  0,7578          NaN          NaN  
1  0,7255          NaN          NaN  
2  0,7502          NaN          NaN  
3  0,7867          NaN          NaN  
4  0,7888          NaN          NaN

Notice how some columns have commas for decimals and we have both a Date and Time column? We can handle that:

In [4]:
df = pd.read_csv('AirQualityUCI.csv', sep=';', decimal=',', parse_dates=[['Date', 'Time']])
df.head()

Date_Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0  10/03/2004 18.00.00     2.6       1360.0     150.0      11.9   
1  10/03/2004 19.00.00     2.0       1292.0     112.0       9.4   
2  10/03/2004 20.00.00     2.2       1402.0      88.0       9.0   
3  10/03/2004 21.00.00     2.2       1376.0      80.0       9.2   
4  10/03/2004 22.00.00     1.6       1272.0      51.0       6.5   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0         1046.0    166.0        1056.0    113.0        1692.0       1268.0   
1          955.0    103.0        1174.0     92.0        1559.0        972.0   
2          939.0    131.0        1140.0    114.0        1555.0       1074.0   
3          948.0    172.0        1092.0    122.0        1584.0       1203.0   
4          836.0    131.0        1205.0    116.0        1490.0       1110.0   

      T    RH      AH  Unnamed: 15  Unnamed: 16  
0  13.6  48.9  0.7578          NaN          NaN  
1  13.3  47.7  0.7255          NaN          NaN  
2  11.9  54.0  0.7502          NaN          NaN  
3  11.0  60.0  0.7867          NaN          NaN  
4  11.2  59.6  0.7888          NaN          NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 16 columns):
Date_Time        9471 non-null object
CO(GT)           9357 non-null float64
PT08.S1(CO)      9357 non-null float64
NMHC(GT)         9357 non-null float64
C6H6(GT)         9357 non-null float64
PT08.S2(NMHC)    9357 non-null float64
NOx(GT)          9357 non-null float64
PT08.S3(NOx)     9357 non-null float64
NO2(GT)          9357 non-null float64
PT08.S4(NO2)     9357 non-null float64
PT08.S5(O3)      9357 non-null float64
T                9357 non-null float64
RH               9357 non-null float64
AH               9357 non-null float64
Unnamed: 15      0 non-null float64
Unnamed: 16      0 non-null float64
dtypes: float64(15), object(1)
memory usage: 1.2+ MB


Notice Pandas also did the type conversions for us.

9471 rows withn 9357 non-null. Where are the rotten apples?

In [6]:
9471 - 9357

114

In [7]:
df.tail()

Date_Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  PT08.S2(NMHC)  \
9466   nan nan     NaN          NaN       NaN       NaN            NaN   
9467   nan nan     NaN          NaN       NaN       NaN            NaN   
9468   nan nan     NaN          NaN       NaN       NaN            NaN   
9469   nan nan     NaN          NaN       NaN       NaN            NaN   
9470   nan nan     NaN          NaN       NaN       NaN            NaN   

      NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)   T  RH  AH  \
9466      NaN           NaN      NaN           NaN          NaN NaN NaN NaN   
9467      NaN           NaN      NaN           NaN          NaN NaN NaN NaN   
9468      NaN           NaN      NaN           NaN          NaN NaN NaN NaN   
9469      NaN           NaN      NaN           NaN          NaN NaN NaN NaN   
9470      NaN           NaN      NaN           NaN          NaN NaN NaN NaN   

      Unnamed: 15  Unnamed: 16  
9466          NaN          NaN  
9467          NaN          NaN  
9468          NaN          NaN  
9469          NaN          NaN  
9470          NaN          NaN

In [8]:
df[-115:]

Date_Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
9356  04/04/2005 14.00.00     2.2       1071.0    -200.0      11.9   
9357              nan nan     NaN          NaN       NaN       NaN   
9358              nan nan     NaN          NaN       NaN       NaN   
9359              nan nan     NaN          NaN       NaN       NaN   
9360              nan nan     NaN          NaN       NaN       NaN   
9361              nan nan     NaN          NaN       NaN       NaN   
9362              nan nan     NaN          NaN       NaN       NaN   
9363              nan nan     NaN          NaN       NaN       NaN   
9364              nan nan     NaN          NaN       NaN       NaN   
9365              nan nan     NaN          NaN       NaN       NaN   
9366              nan nan     NaN          NaN       NaN       NaN   
9367              nan nan     NaN          NaN       NaN       NaN   
9368              nan nan     NaN          NaN       NaN       NaN   
9369              nan nan     NaN          NaN       NaN       NaN   
9370              nan nan     NaN          NaN       NaN       NaN   
9371              nan nan     NaN          NaN       NaN       NaN   
9372              nan nan     NaN          NaN       NaN       NaN   
9373              nan nan     NaN          NaN       NaN       NaN   
9374              nan nan     NaN          NaN       NaN       NaN   
9375              nan nan     NaN          NaN       NaN       NaN   
9376              nan nan     NaN          NaN       NaN       NaN   
9377              nan nan     NaN          NaN       NaN       NaN   
9378              nan nan     NaN          NaN       NaN       NaN   
9379              nan nan     NaN          NaN       NaN       NaN   
9380              nan nan     NaN          NaN       NaN       NaN   
9381              nan nan     NaN          NaN       NaN       NaN   
9382              nan nan     NaN          NaN       NaN       NaN   
9383              nan nan     NaN          NaN       NaN       NaN   
9384              nan nan     NaN          NaN       NaN       NaN   
9385              nan nan     NaN          NaN       NaN       NaN   
...                   ...     ...          ...       ...       ...   
9441              nan nan     NaN          NaN       NaN       NaN   
9442              nan nan     NaN          NaN       NaN       NaN   
9443              nan nan     NaN          NaN       NaN       NaN   
9444              nan nan     NaN          NaN       NaN       NaN   
9445              nan nan     NaN          NaN       NaN       NaN   
9446              nan nan     NaN          NaN       NaN       NaN   
9447              nan nan     NaN          NaN       NaN       NaN   
9448              nan nan     NaN          NaN       NaN       NaN   
9449              nan nan     NaN          NaN       NaN       NaN   
9450              nan nan     NaN          NaN       NaN       NaN   
9451              nan nan     NaN          NaN       NaN       NaN   
9452              nan nan     NaN          NaN       NaN       NaN   
9453              nan nan     NaN          NaN       NaN       NaN   
9454              nan nan     NaN          NaN       NaN       NaN   
9455              nan nan     NaN          NaN       NaN       NaN   
9456              nan nan     NaN          NaN       NaN       NaN   
9457              nan nan     NaN          NaN       NaN       NaN   
9458              nan nan     NaN          NaN       NaN       NaN   
9459              nan nan     NaN          NaN       NaN       NaN   
9460              nan nan     NaN          NaN       NaN       NaN   
9461              nan nan     NaN          NaN       NaN       NaN   
9462              nan nan     NaN          NaN       NaN       NaN   
9463              nan nan     NaN          NaN       NaN       NaN   
9464              nan nan     NaN          NaN       NaN       NaN   
9465              nan nan     NaN          NaN       NaN       NaN   
9466              nan nan 

Looks like the bottom 114 lines are the problem. Let's drop them.

In [9]:
new_df = df[:-114]

In [10]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 16 columns):
Date_Time        9357 non-null object
CO(GT)           9357 non-null float64
PT08.S1(CO)      9357 non-null float64
NMHC(GT)         9357 non-null float64
C6H6(GT)         9357 non-null float64
PT08.S2(NMHC)    9357 non-null float64
NOx(GT)          9357 non-null float64
PT08.S3(NOx)     9357 non-null float64
NO2(GT)          9357 non-null float64
PT08.S4(NO2)     9357 non-null float64
PT08.S5(O3)      9357 non-null float64
T                9357 non-null float64
RH               9357 non-null float64
AH               9357 non-null float64
Unnamed: 15      0 non-null float64
Unnamed: 16      0 non-null float64
dtypes: float64(15), object(1)
memory usage: 1.1+ MB


In [11]:
new_df.describe()

CO(GT)  PT08.S1(CO)     NMHC(GT)     C6H6(GT)  PT08.S2(NMHC)  \
count  9357.000000  9357.000000  9357.000000  9357.000000    9357.000000   
mean    -34.207524  1048.990061  -159.090093     1.865683     894.595276   
std      77.657170   329.832710   139.789093    41.380206     342.333252   
min    -200.000000  -200.000000  -200.000000  -200.000000    -200.000000   
25%       0.600000   921.000000  -200.000000     4.000000     711.000000   
50%       1.500000  1053.000000  -200.000000     7.900000     895.000000   
75%       2.600000  1221.000000  -200.000000    13.600000    1105.000000   
max      11.900000  2040.000000  1189.000000    63.700000    2214.000000   

           NOx(GT)  PT08.S3(NOx)      NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
count  9357.000000   9357.000000  9357.000000   9357.000000  9357.000000   
mean    168.616971    794.990168    58.148873   1391.479641   975.072032   
std     257.433866    321.993552   126.940455    467.210125   456.938184   
min    -200.000000   -200.000000  -200.000000   -200.000000  -200.000000   
25%      50.000000    637.000000    53.000000   1185.000000   700.000000   
50%     141.000000    794.000000    96.000000   1446.000000   942.000000   
75%     284.000000    960.000000   133.000000   1662.000000  1255.000000   
max    1479.000000   2683.000000   340.000000   2775.000000  2523.000000   

                 T           RH           AH  Unnamed: 15  Unnamed: 16  
count  9357.000000  9357.000000  9357.000000          0.0          0.0  
mean      9.778305    39.485380    -6.837604          NaN          NaN  
std      43.203623    51.216145    38.976670          NaN          NaN  
min    -200.000000  -200.000000  -200.000000          NaN          NaN  
25%      10.900000    34.100000     0.692300          NaN          NaN  
50%      17.200000    48.600000     0.976800          NaN          NaN  
75%      24.100000    61.900000     1.296200          NaN          NaN  
max      44.600000    88.700000     2.231000          NaN          NaN

In [12]:
new_df.head()

Date_Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0  10/03/2004 18.00.00     2.6       1360.0     150.0      11.9   
1  10/03/2004 19.00.00     2.0       1292.0     112.0       9.4   
2  10/03/2004 20.00.00     2.2       1402.0      88.0       9.0   
3  10/03/2004 21.00.00     2.2       1376.0      80.0       9.2   
4  10/03/2004 22.00.00     1.6       1272.0      51.0       6.5   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0         1046.0    166.0        1056.0    113.0        1692.0       1268.0   
1          955.0    103.0        1174.0     92.0        1559.0        972.0   
2          939.0    131.0        1140.0    114.0        1555.0       1074.0   
3          948.0    172.0        1092.0    122.0        1584.0       1203.0   
4          836.0    131.0        1205.0    116.0        1490.0       1110.0   

      T    RH      AH  Unnamed: 15  Unnamed: 16  
0  13.6  48.9  0.7578          NaN          NaN  
1  13.3  47.7  0.7255          NaN          NaN  
2  11.9  54.0  0.7502          NaN          NaN  
3  11.0  60.0  0.7867          NaN          NaN  
4  11.2  59.6  0.7888          NaN          NaN

Need to drop columns that are missing all values: 

In [13]:
drop_col = ['Unnamed: 15', 'Unnamed: 16']
new_df.drop(drop_col, axis= 1, inplace=True )

/Users/mbusch/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [14]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 14 columns):
Date_Time        9357 non-null object
CO(GT)           9357 non-null float64
PT08.S1(CO)      9357 non-null float64
NMHC(GT)         9357 non-null float64
C6H6(GT)         9357 non-null float64
PT08.S2(NMHC)    9357 non-null float64
NOx(GT)          9357 non-null float64
PT08.S3(NOx)     9357 non-null float64
NO2(GT)          9357 non-null float64
PT08.S4(NO2)     9357 non-null float64
PT08.S5(O3)      9357 non-null float64
T                9357 non-null float64
RH               9357 non-null float64
AH               9357 non-null float64
dtypes: float64(13), object(1)
memory usage: 1023.5+ KB


Next we need to convert the date and time to an integer so we can use them for KNN imputation. The way to do this is use **time since epoch.** (Google is your friend).

In this case our original date time reader failed us. Even though it merged the columns, it did not create a datetime type. This is due in large part to the non-standard time format. Let's correct both of those problems now.

In [15]:
import datetime as dt
from dateutil.parser import parse

def dt2epoch(value):
    d = parse(value)
    epoch = (d - dt.datetime(1970,1,1)).total_seconds()
    return epoch    


def colonify(value):
    vals = value.split(' ')
    vals[1] = vals[1].replace('.', ':')
    return ' '.join(vals)
new_df['Date_Time'] = new_df['Date_Time'].apply(colonify)
new_df['Epoch'] = new_df['Date_Time'].apply(dt2epoch)

/Users/mbusch/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/mbusch/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [16]:
new_df.head()

Date_Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0  10/03/2004 18:00:00     2.6       1360.0     150.0      11.9   
1  10/03/2004 19:00:00     2.0       1292.0     112.0       9.4   
2  10/03/2004 20:00:00     2.2       1402.0      88.0       9.0   
3  10/03/2004 21:00:00     2.2       1376.0      80.0       9.2   
4  10/03/2004 22:00:00     1.6       1272.0      51.0       6.5   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0         1046.0    166.0        1056.0    113.0        1692.0       1268.0   
1          955.0    103.0        1174.0     92.0        1559.0        972.0   
2          939.0    131.0        1140.0    114.0        1555.0       1074.0   
3          948.0    172.0        1092.0    122.0        1584.0       1203.0   
4          836.0    131.0        1205.0    116.0        1490.0       1110.0   

      T    RH      AH         Epoch  
0  13.6  48.9  0.7578  1.096826e+09  
1  13.3  47.7  0.7255  1.096830e+09  
2  11.9  54.0  0.7502  1.096834e+09  
3  11.0  60.0  0.7867  1.096837e+09  
4  11.2  59.6  0.7888  1.096841e+09